### PR TITLE
issue#1 and issue#2 resolved

### PR DESCRIPTION
**Pull request by classicmatsuo**
from my understanding, you no longer need the 'gatsby-theme-minimal-example' folder at the top level, the one thats the same level as 'gatsby-starter-default'. 
shadowing does need it in the same src folder, so the folder  'gatsby-theme-minimal-example' at the same level as 'components' is the one you would want to use.

by deleting the top level folder, this resolves issue#1 and issue#2. for right now, i've just gone ahead and commented out the queries in that folders template files (article.js, page.js, section.js)

the section.js file has been modified to output the correct layout and perform a query.

additionally, I went ahead and changed the name of the query back to ArticleQuery, since the top level folder has had the queries commented out.

http://localhost:8000/article/danish-fontina-cheesy-feet-red and http://localhost:8000/section/about are working now.

### CODE REVIEW

**Comment by laradevitt** [comment]
Hey @classicmatsuo, I really appreciate this. I'm a little confused, though. I set up this workspace to demo the issues that arose for me while developing a theme (represented here as *gatsby-theme-minimal-example*).  I can only test the theme as a dependency of a gatsby site, which is what *gatsby-starter-default* is for. See [Setting up Yarn Workspaces for Theme Development](https://www.gatsbyjs.org/blog/2019-05-22-setting-up-yarn-workspaces-for-theme-development/).

If I delete the theme (gatsby-theme-minimal-example), as you suggest, then there is nothing to shadow?? Unless I am misunderstanding, when you commented out the original components you basically turned the components in *gatsby-starter-default* into regular ol' components.

**Comment by classicmatsuo** [comment]
@laradevitt youre correct. ignore my pr and ill take another look at this

**Comment by laradevitt** [comment]
I appreciate your taking the time in any case. Theme development is a little bit tricky for sure. 😄

**Comment by laradevitt** [comment]
Hey @classicmatsuo, if you are *not* running Windows, could you let me know if you can reproduce the issue in #1? I don't think this is Windows-related but I would like to be able to confirm that. 

1. Clone repo
2. `cd` into project
3. Run `yarn` to install packages
4. Run `yarn develop` to start the dev server.

Navigate to: */section/about*. There should be no data. 
Navigate to: */article/danish-fontina-cheesy-feet-red* - the data should be displayed.

If you are able to reproduce it, it would be helpful if you could leave a comment saying so (with environment info) in the original issue: https://github.com/gatsbyjs/gatsby/issues/19980

Thanks!

**Pull request closed without merging**
